"""
Smart Expense Tracker API.

Endpoints:
    POST   /expenses            Add an expense
    GET    /expenses            List all expenses (optional ?category= filter)
    GET    /expenses/totals     Overall total + total by category
    DELETE /expenses/{id}       Delete an expense by id

Interactive API docs are auto-generated by FastAPI at /docs (Swagger UI)
and /redoc.
"""
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, status

from .models import Expense, ExpenseCreate, TotalsResponse, CategoryTotal
from .storage import ExpenseStore

app = FastAPI(
    title="Smart Expense Tracker API",
    description="A minimal REST API for tracking personal expenses.",
    version="1.0.0",
)

store = ExpenseStore()


@app.post("/expenses", response_model=Expense, status_code=status.HTTP_201_CREATED)
def add_expense(expense: ExpenseCreate) -> Expense:
    """Create a new expense. The server assigns the id."""
    return store.add(expense)


@app.get("/expenses", response_model=list[Expense])
def list_expenses(
    category: Optional[str] = Query(
        default=None, description="Filter by category (case-insensitive)"
    )
) -> list[Expense]:
    """Return all expenses, or only those matching `category` if provided."""
    return store.list_all(category=category)


@app.get("/expenses/totals", response_model=TotalsResponse)
def get_totals() -> TotalsResponse:
    """Return the overall total and a per-category breakdown."""
    overall, by_category = store.totals()
    return TotalsResponse(
        overall_total=overall,
        by_category=[CategoryTotal(category=c, total=t) for c, t in by_category.items()],
    )


@app.delete("/expenses/{expense_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_expense(expense_id: int) -> None:
    """Delete an expense by id. Returns 404 if it doesn't exist."""
    deleted = store.delete(expense_id)
    if not deleted:
        raise HTTPException(status_code=404, detail=f"Expense {expense_id} not found")
